conn=net.createConnection(net.TCP, 0)
conn:on("receive", function(conn, payload)
  print(payload)
end)
conn:connect(80,'184.106.153.149')
conn:send("GET /update?key=yourKEY&field1=16 HTTP/1.1\r\n")
conn:send("Host: api.thingspeak.com\r\n")
conn:send("Accept: */*\r\n")
conn:send("User-Agent: Mozilla/4.0 (compatible; esp8266 Lua; Windows NT 5.1)\r\n")
conn:send("\r\n")
